outfile: main.o std_add.o std_delete.o std_show.o std_sort.o std_deleteall.o std_reverse.o std_save.o std_count.o  std_mod.o std_exit.o
	cc main.c std_add.c std_delete.c std_show.c std_sort.c std_deleteall.c std_reverse.c std_save.c std_count.c  std_mod.c std_exit.c -o student

main.o: main.c
	cc -c main.c -o main.o

std_add.o:std_add.c
	cc -c std_add.c -o std_add.o

std_delete.o:std_delete.c
	cc -c std_delete.c -o std_delete.o

std_show.o:std_show.c
	cc -c std_show.c -o std_show.o

std_sort.o:std_sort.c
	cc -c std_sort.c -o std_sort.o

std_deleteall.o:std_deleteall.c
	cc -c std_deleteall.c -o std_deleteall.o

std_rev.o:std_rev.c
	cc -c std_rev.c -o std_rev.o

std_count.o:std_count.c
	cc -c std_count.c -o std_count.o

std_exit.o:std_exit.c
	cc -c std_exit.c -o std_exit.o

std_mod.o:std_mod.c
	cc -c std_mod.c -o std_mod.o

std_save.o:std_save.c
	cc -c std_save.c -o std_save.o

