outfile:begin.o end.o main.o middle.o save_file.o count.o print_rec.o
	cc begin.c end.c main.c middle.c save_file.c count.c print_rec.c -o outfile
begin.o:begin.c
	cc -c begin.c -o begin.o

end.o:end.c
	cc -c end.c -o end.o

main.o:main.c
	cc -c main.c -o main.o

middle.o:middle.c
	cc -c middle.c -o middle.o

save_file.o:save_file.c
	cc -c save_file.c -o save_file.o

count.o:count.c
	cc -c count.c -o count.o

print_rec.o: print_rec.c
	cc -c print_rec.c -o print_rec.o
